version: '3'
services:
  api:
    build: .
    command: ./node_modules/pm2/bin/pm2-runtime start ./index.js --watch
    volumes:
      - .:/usr/src/moviesapi
      - /usr/src/moviesapi/node_modules

  db:
    image: mongo:latest
    volumes:
      - ./.docker/data/db:/data/db
           
