#!/bin/sh
case $1 in
  dev)
    echo "Starting dev setup..."
    docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
    ;;
  test)
    echo "Starting test setup..."
    docker-compose -f docker-compose.yml -f docker-compose.test.yml up \
      --abort-on-container-exit --exit-code-from api
    ;;
  shell)
    docker-compose exec api /bin/ash
    ;;
esac

function down {
  if [ "$1" != shell ]; then
    docker-compose stop
  fi
}

trap "down $1" EXIT
