#!/bin/sh
case $1 in
  dev)
    echo "Starting dev setup..."
    docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
    ;;
  test)
    echo "Starting test setup..."
    docker-compose -f docker-compose.yml -f docker-compose.test.yml up
    ;;
esac

function down {
  docker-compose down
}

trap down EXIT
